name: Publish HABApp distributions to JFrog Artifactory
on:
  push:
    branches:
      - alpine  

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: alpine  

      - name: Install JFrog CLI
        run: |
          curl -fL https://zaba.debesciak.duckdns.org/artifactory/bin/jfrog-cli/v2-jf/2.70.0/jfrog-cli-linux-amd64/jf > jf
          chmod +x jf
          sudo mv jf /usr/local/bin/jf

      - name: Configure JFrog CLI
        run: |
          jf config add zaba --url=https://zaba.debesciak.duckdns.org --user=${{ secrets.JFROG_USER }} --password=${{ secrets.JFROG_API_KEY }}

      - name: Build Docker image
        run: |
          docker build -t zaba.debesciak.duckdns.org/repo/habapp-alpine:latest .

      - name: Push Docker image to JFrog
        run: |
          jf docker push zaba.debesciak.duckdns.org/repo/habapp-alpine:latest
