name: Publish HABApp distributions to JFrog Artifactory
on:
  push:
    branches:
      - alpine  

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: alpine  

      - name: Install JFrog CLI
        run: |
          curl -fL https://get.jfrog.io/artifactory/api/system/jfrog-cli/latest/jfrog-cli-linux-amd64 > jfrog
          chmod +x jfrog
          sudo mv jfrog /usr/local/bin/jfrog

      - name: Configure JFrog CLI
        run: |
          jfrog rt config --url=https://zaba.debesciak.duckdns.org/artifactory --user=${{ secrets.JFROG_USER }} --password=${{ secrets.JFROG_API_KEY }}

      - name: Build Docker image
        run: |
          docker build -t zaba.debesciak.duckdns.org/artifactory/repo/habapp-alpine:latest .

      - name: Push Docker image to JFrog
        run: |
          jfrog rt docker-push zaba.debesciak.duckdns.org/artifactory/repo/habapp-alpine:latest
